### ISSUE TITLE
Cannot read property 'profiles' of undefined

### ISSUE THREAD

**Issue by laxman225** [ribeiro-rodrigo/node-config-client#1]
There seems to be a problem with validateconfig.

Cannot read property 'profiles' of undefined
    at validateConfig (/opt/banking/node_modules/node-config-client/index.js:32:64)

**Comment by ribeiro-rodrigo** [comment]
Thanks for watching. The problem was corrected in commit seems config is not passed to validateConfig. The correction has already been immersed in the master branch.
